project:
  type: book  
  output-dir: docs

book:
  title: "Evaluation of the Threat of Shark-infested Tornados"
  author: "Brett Stewart"
  page-footer:
    left: "Copyright 2025, Brett Stewart"
  chapters:
    - index.qmd
    - draft-exec-summary.qmd
    - introduction.qmd
    - methods.qmd
    - Results.qmd
    - conclusion.qmd
    - references.qmd
  appendices:
    - draft-data-doc.qmd
    - draft-results.qmd
    - draft-intro-conclusions.qmd
    - Sharknader.R

bibliography: references.bib

format:
  html:
    highlight-style: a11y
    theme: cosmo
  pdf:
    documentclass: scrreprt



