---
title: "Conclusion"
format: html
editor: visual
---

After analyzing data from reputable sources on both shark populations and storm events, findings suggest that tornadoes with the ability to transport sharks inland are extremely unlikely to occur, and nothing to be concerned about. The set of conditions needed for sharks to be lifted from the ocean and transported inland is virtually nonexistent based on historical data. One limitation of this analysis that impacted the numerical results were missing data values for the certain aspects of tornado data that were emphasized. Future avenues of research relating to this analysis could include a study as to whether sharks are adept at sensing severe weather, or if they are effective in reacting to its arrival. Another potential avenue for research could include studying the preparedness of zoos in instances of tornadoes, as a dangerous or invasive animal escaping its assigned habitat due to the destruction of a tornado would be horrible.

On the business side of things, the financial risk posed by a Sharknado is negligible. There is no need to adjust any actuarial models, insurance premiums, or any related things of that nature due to the threat of shark infested tornados. Although media that we consume can create fear within in our minds, this analysis is good example that our business should continue to function based on reality and data.
