---
title: "Draft: Data Documentation"
---


@StormEventsDatabasea

The National Centers for Environmental Information(NCEI) data in this report relating to storm events was collected from the National Weather Service(NWS), who receives their information from a variety of sources. The data was recorded to users to search for various types of recorded storms throughout recent history. The data contains records of storm events from all over the country dating from the beginning of January 1950 until November of 2024. For each year, there is a separate file dedicated to either storm details, storm fatalities, or storm locations. Only tornadoes were recorded for the first five years of data, thunderstorm wind and hail were added for the following 41 years, and all other event types were added from that point until now.

The various sources that contribute data to the NWS include management officials from the county, state and federal levels, local law enforcement officials, skywarn spotters, damage surveys, newspaper clipping services, the general public, and the insurance industry. Once the data is collected by the NWS, it is validated, entered, and sent to the NCEI approximately 75 days after each data month. Although it is validated by the NWS, they acknowledge that the NWS does not guarantee the accuracy or validity of information due to resource constraints. Even knowing this, it is nice that the datasets are of high quality.

The data files are structured in csv format, with each type of file(details,locations,fatalities) having its own comprehensible data dictionary given in the zip file. One variable in the dataset that will be of use is ez_type and particularly when it is equal to M (Marine). This variable describes where the storm event happened, and tornados occuring in a marine location are applicable to a hypothetical sharknado occurance. Another dataset variable tor_f_scale describes tornado strength on a scale ranging from EF0 to EF5. Less severe tornaodos are not likely to transport sharks. Beginning and ending longitudes and latitudes of storm damage paths may also be of use and are seen in the variable format begin_lon, end_lat etc. On the NOAA website it is stated that the files can be viewed in Excel and other spreadsheet applications. 

@nationaloceanicandatmosphericadministrationnoaaNMFSBLLData

The data in this report relating to shark populations in coastal regions was collected by the fisheries department of the NOAA. The dataset was formed in order to track shark abundance and it is used to assess the stock of coastal sharks in United States waters in the western North Atlantic ocean and also in the Gulf of Mexico. The data collection time frame spans the months of July through September in the years of 2010 until 2024, and was collected from sharks captured in the Atlantic Ocean and Gulf of Mexico.


The data collection process involves dividing the different ranges of ocean depths into strata and then taking samples at 300 randomly selected stations. Sharks were caught, tagged, surveyed, and then usually released. The data is structured in Excel chronologically. Unlike the weather data, the data contributions do not come from a variety of sources and should therefore have a higher likelihood to be valid and of good quality. It is suggested that the best species of shark for data analysis include the sharpnose, blacktip, sandbar, blacknose, nurse, and tiger. GPS measurement systems were used to determine longitude and latitude of shark capture, and a measurement tool that was not disclosed was used to measure precaudal length, standard length, fork length, natural length and stretched length. One group of variables within the dataset that will be of use are the latitudinal and longitudinal locations of the shark capturing stations. The station depth will also be useful since sharks captured deeper than certain depths are unlikely to be picked up by a tornado. The shark length measurement variables are measured in millimeters and may not be of use. The dataset is high quality and has minimal missing data cells.

