---
title: "Draft: Intro/Conclusions"
---
Introduction

The 2013 sci-fi film Sharknado has introduced the potential issue of bizarre storms, specifically tornados that have the capability to transport sharks from oceanic waters to mainland. As an insurance company, the probability of such an occurrence should be properly calculated or estimated. A big reason why we want to know the probability of such an occurrence is due to an unforeseen possible increase in insurance payouts related to such a catastrophic event. Being financially prepared for those payouts is a necessity for our business to continue to thrive.

Our research question we will explore is how serious a Sharknado threat is to our bottom line. Our approach to answering this question involves analysis using data gathered from reputable government agencies on both shark populations and storm events. 

Conclusion

After analyzing data from reputable sources on both shark populations and storm events, findings suggest that tornados with the ability to transport sharks inland are extremely unlikely to occur, and nothing to be concerned about. The set of conditions needed for sharks to be lifted from the ocean and transported inland is virtually nonexistent based on historical data.

On the business side of things, the financial risk posed by a Sharknado is negligible. There is no need to adjust any actuarial models, insurance premiums, or any related things of that nature due to the threat of shark infested tornados. Although media we consume can create fear within in our minds, this analysis is good example that our business should continue to function based on reality and data. 
